# Project: Project1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe -D__DEBUG__
CC   = gcc.exe -D__DEBUG__
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"C:/Users/Nick/Desktop/Main desktop files/C++/Coding programs/Dev-Cpp/lib" -lglut32 -lglu32 -lopengl32 -lwinmm -lgdi32 -lopengl32 -lopengl32  -lglut -lmingw32  -g3 
INCS =  -I"C:/Users/Nick/Desktop/Main desktop files/C++/Coding programs/Dev-Cpp/include" 
CXXINCS =  -I"C:/Users/Nick/Desktop/Main desktop files/C++/Coding programs/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Users/Nick/Desktop/Main desktop files/C++/Coding programs/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Users/Nick/Desktop/Main desktop files/C++/Coding programs/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Users/Nick/Desktop/Main desktop files/C++/Coding programs/Dev-Cpp/include/c++/3.4.2"  -I"C:/Users/Nick/Desktop/Main desktop files/C++/Coding programs/Dev-Cpp/include" 
BIN  = Project1.exe
CXXFLAGS = $(CXXINCS)   -g3
CFLAGS = $(INCS)   -g3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Project1.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Project1.exe" $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
